name = "TNS Miniseason 5"
author = "TheDeathlyCow"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebe9a50e6dc682ff8cfe7b4591896b1cedb683b4cf79b19375c5babcccdf8c7a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
