name = "TNS Miniseason 5"
author = "TheDeathlyCow"
version = "1.1.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2097b0ed2b561c03cc23e8692548161f9630fe13717308a496df437ec066950"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
