name = "Miniseason5"
author = "TheDeathlyCow"
version = "1.0.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee4bfa7154bde46f5c3b16276eb53771d71554c2035918055e0cb71c3a92d224"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
