name = "Miniseason5"
author = "TheDeathlyCow"
version = "1.0.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daf4058c441feef08e5c055f25d7dfdae6a579db8b67298de532400746635514"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
