name = "Miniseason5"
author = "TheDeathlyCow"
version = "1.0.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb7f68009f70ba98b940caa0acf53228127be59b2490925031388a8eb2237a14"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
