name = "TNS Miniseason 5"
author = "TheDeathlyCow"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "978b07a5380df614474ff3233c7784f6ae6a566dcca1227e4f978bd6a259bb5a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
