name = "TNS Miniseason 5"
author = "TheDeathlyCow"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2747991c1c5b9c3ce0fd49cf2fb3fc661f602f0bb46a4e119e09eb00562eb40b"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
