name = "TNS Miniseason 5"
author = "TheDeathlyCow"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ca9f824af2ca923c566c465da174005f9f2ddf2f815822651b7c87eee681682"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
